[package]
name = "ex_moq"
version = "0.1.0"
authors = []
edition = "2024"
rust-version = "1.88.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
moq-native = "0.18.3"
hang = "0.19.5"
moq-mux = "0.7.6"
url = "2.5.8"
rustler = "0.38.0"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
bytes = "1"
anyhow = "1.0.102"
