defmodule Membrane.MoQ.Test.Relay do
  @moduledoc """
  NOTE: This test support module was LLM-generated.

  Provides a MoQ relay for integration tests.

  Ensures TCP is used for lossless transport,
  but groups can still be dropped as part of eviction policies.

  Cleanup of the spawned relay is layered:

    * `ExUnit.after_suite/1` (registered on spawn) stops the server once the
      suite finishes, stopping the relay and deleting the generated config.
    * Should the VM die without running that callback (e.g. SIGKILL),
      muontrap's shim process still reaps the relay: it kills it the moment
      its pipe to the VM closes.
  """

  use GenServer

  @ready_timeout_ms 15_000
  @probe_interval_ms 100

  @type relay :: %{url: String.t(), disable_tls_verify?: boolean()}

  @spec ensure!() :: relay()
  def ensure!() do
    pid =
      case GenServer.start(__MODULE__, nil, name: __MODULE__) do
        {:ok, pid} ->
          pid

        {:error, {:already_started, pid}} ->
          pid

        {:error, reason} ->
          raise "failed to start the test relay: #{Exception.format_exit(reason)}"
      end

    GenServer.call(pid, :relay, :infinity)
  end

  @doc "Stops the spawned relay, if any. Registered as an `ExUnit.after_suite/1` callback."
  @spec stop() :: :ok
  def stop() do
    case GenServer.whereis(__MODULE__) do
      nil -> :ok
      pid -> GenServer.stop(pid)
    end
  end

  @impl true
  def init(nil) do
    binary = find_binary!()
    port_number = free_port!()
    config_path = write_config!(port_number)

    {:ok, daemon} =
      MuonTrap.Daemon.start_link(binary, [config_path],
        stderr_to_stdout: true,
        log_output: :debug,
        log_prefix: "moq-relay: ",
        exit_status_to_reason: &{:moq_relay_exited, &1}
      )

    await_ready!(port_number)

    ExUnit.after_suite(fn _stats -> stop() end)

    {:ok,
     %{
       relay: %{url: "tcp://127.0.0.1:#{port_number}", disable_tls_verify?: false},
       daemon: daemon,
       config_path: config_path
     }}
  end

  @impl true
  def terminate(_reason, state) do
    # Stopping the daemon makes muontrap's shim kill the relay.
    if Process.alive?(state.daemon), do: GenServer.stop(state.daemon)
    File.rm(state.config_path)
    :ok
  end

  @impl true
  def handle_call(:relay, _from, state), do: {:reply, state.relay, state}

  defp find_binary!() do
    System.get_env("MOQ_RELAY") || System.find_executable("moq-relay") ||
      raise """
      no moq-relay binary for the integration tests; provide one of:
        * MOQ_RELAY — path to a moq-relay binary
        * moq-relay on $PATH (e.g. installed with `cargo install moq-relay`)
      """
  end

  defp free_port!() do
    {:ok, socket} = :gen_tcp.listen(0, reuseaddr: true)
    {:ok, port_number} = :inet.port(socket)
    :ok = :gen_tcp.close(socket)
    port_number
  end

  defp write_config!(port_number) do
    path = Path.join(System.tmp_dir!(), "membrane-moq-test-relay-#{port_number}.toml")

    File.write!(path, """
    # Generated by #{inspect(__MODULE__)}; safe to delete.
    [log]
    level = "info"

    [server]
    tcp.bind = "127.0.0.1:#{port_number}"

    [auth]
    public = ""
    """)

    path
  end

  defp await_ready!(port_number) do
    deadline = System.monotonic_time(:millisecond) + @ready_timeout_ms
    await_ready_loop(port_number, deadline)
  end

  defp await_ready_loop(port_number, deadline) do
    cond do
      probe(port_number) ->
        :ok

      System.monotonic_time(:millisecond) > deadline ->
        raise """
        moq-relay did not become ready within #{@ready_timeout_ms} ms; \
        its output is forwarded to the Logger at debug level
        """

      true ->
        Process.sleep(@probe_interval_ms)
        await_ready_loop(port_number, deadline)
    end
  end

  defp probe(port_number) do
    case :gen_tcp.connect(~c"127.0.0.1", port_number, [:binary, active: false], 1_000) do
      {:ok, socket} ->
        :gen_tcp.close(socket)
        true

      {:error, _reason} ->
        false
    end
  end
end
