defmodule Membrane.MoQ.Test.Relay do
  @moduledoc """
  NOTE: This test support module was LLM-generated.

  Provides a MoQ relay for integration tests.

  `ensure!/0` returns `%{url: url, disable_tls_verify?: boolean}`:

    * If `RELAY_URL` is set, that relay is used as-is and nothing is spawned.
    * Otherwise a `moq-relay` binary (`MOQ_RELAY` env var, or found on `$PATH`)
      is spawned on a random free port with a self-signed certificate and
      anonymous auth. The instance is shared by all test modules in the run.

  Cleanup of the spawned relay is layered:

    * `ExUnit.after_suite/1` (registered on spawn) stops the server once the
      suite finishes, stopping the relay and deleting the generated config.
    * Should the VM die without running that callback (e.g. SIGKILL),
      muontrap's shim process still reaps the relay: it kills it the moment
      its pipe to the VM closes.
  """

  use GenServer

  @localhost_hosts ["localhost", "127.0.0.1", "::1"]
  @ready_timeout_ms 15_000
  @probe_interval_ms 100

  @type relay :: %{url: String.t(), disable_tls_verify?: boolean()}

  @spec ensure!() :: relay()
  def ensure!() do
    case System.get_env("RELAY_URL") do
      nil ->
        spawned_relay!()

      url ->
        # A local relay presents a self-signed certificate; a remote one is
        # expected to present a valid certificate.
        %{url: url, disable_tls_verify?: URI.parse(url).host in @localhost_hosts}
    end
  end

  defp spawned_relay!() do
    # Unlinked and named, so one relay serves every test module in the run.
    pid =
      case GenServer.start(__MODULE__, nil, name: __MODULE__) do
        {:ok, pid} ->
          pid

        {:error, {:already_started, pid}} ->
          pid

        {:error, reason} ->
          raise "failed to start the test relay: #{Exception.format_exit(reason)}"
      end

    GenServer.call(pid, :relay, :infinity)
  end

  @doc "Stops the spawned relay, if any. Registered as an `ExUnit.after_suite/1` callback."
  @spec stop() :: :ok
  def stop() do
    case GenServer.whereis(__MODULE__) do
      nil -> :ok
      pid -> GenServer.stop(pid)
    end
  end

  @impl true
  def init(nil) do
    binary = find_binary!()
    port_number = free_port!()
    config_path = write_config!(port_number)

    {:ok, daemon} =
      MuonTrap.Daemon.start_link(binary, [config_path],
        stderr_to_stdout: true,
        log_output: :debug,
        log_prefix: "moq-relay: ",
        exit_status_to_reason: &{:moq_relay_exited, &1}
      )

    await_ready!(port_number)

    ExUnit.after_suite(fn _stats -> stop() end)

    {:ok,
     %{
       relay: %{url: "https://localhost:#{port_number}", disable_tls_verify?: true},
       daemon: daemon,
       config_path: config_path
     }}
  end

  @impl true
  def terminate(_reason, state) do
    # Stopping the daemon makes muontrap's shim kill the relay.
    if Process.alive?(state.daemon), do: GenServer.stop(state.daemon)
    File.rm(state.config_path)
    :ok
  end

  @impl true
  def handle_call(:relay, _from, state), do: {:reply, state.relay, state}

  defp find_binary!() do
    System.get_env("MOQ_RELAY") || System.find_executable("moq-relay") ||
      raise """
      no MoQ relay available for the integration tests; provide one of:
        * RELAY_URL — URL of an already-running relay
        * MOQ_RELAY — path to a moq-relay binary
        * moq-relay on $PATH (e.g. installed with `cargo install moq-relay`)
      """
  end

  # The relay binds the same port number twice: QUIC over UDP (`[server]`) and
  # the plain-HTTP readiness endpoint over TCP (`[web.http]`). Take a UDP port
  # from the OS and keep it only if the same number is also free on TCP.
  # The sockets are closed before the relay spawns, so another process could
  # still grab the port in between; unlikely enough for a test helper.
  defp free_port!(attempts \\ 10)

  defp free_port!(0) do
    raise "could not find a port free on both UDP and TCP for the test relay"
  end

  defp free_port!(attempts) do
    {:ok, udp_socket} = :gen_udp.open(0, reuseaddr: true)
    {:ok, port_number} = :inet.port(udp_socket)

    case :gen_tcp.listen(port_number, reuseaddr: true) do
      {:ok, tcp_socket} ->
        :ok = :gen_tcp.close(tcp_socket)
        :ok = :gen_udp.close(udp_socket)
        port_number

      {:error, _reason} ->
        :ok = :gen_udp.close(udp_socket)
        free_port!(attempts - 1)
    end
  end

  defp write_config!(port_number) do
    path = Path.join(System.tmp_dir!(), "membrane-moq-test-relay-#{port_number}.toml")

    File.write!(path, """
    # Generated by #{inspect(__MODULE__)}; safe to delete.
    [log]
    level = "info"

    [server]
    listen = "[::]:#{port_number}"
    # Self-signed certificate; clients connect with TLS verification disabled.
    tls.generate = ["localhost"]

    # Serves /certificate.sha256 over plain HTTP, used as the readiness probe.
    [web.http]
    listen = "[::]:#{port_number}"

    [auth]
    public = ""
    """)

    path
  end

  defp await_ready!(port_number) do
    deadline = System.monotonic_time(:millisecond) + @ready_timeout_ms
    await_ready_loop(port_number, deadline)
  end

  defp await_ready_loop(port_number, deadline) do
    cond do
      probe(port_number) ->
        :ok

      System.monotonic_time(:millisecond) > deadline ->
        raise """
        moq-relay did not become ready within #{@ready_timeout_ms} ms; \
        its output is forwarded to the Logger at debug level
        """

      true ->
        Process.sleep(@probe_interval_ms)
        await_ready_loop(port_number, deadline)
    end
  end

  # Fetches /certificate.sha256, which the relay serves over plain HTTP once
  # it is up. Hand-rolled over :gen_tcp because Mix prunes the code paths of
  # undeclared OTP apps like :inets in the test env.
  defp probe(port_number) do
    case :gen_tcp.connect(~c"127.0.0.1", port_number, [:binary, active: false], 1_000) do
      {:ok, socket} ->
        request =
          "GET /certificate.sha256 HTTP/1.1\r\nhost: localhost\r\nconnection: close\r\n\r\n"

        :ok = :gen_tcp.send(socket, request)
        response = :gen_tcp.recv(socket, 0, 1_000)
        :gen_tcp.close(socket)
        match?({:ok, "HTTP/1.1 200" <> _rest}, response)

      {:error, _reason} ->
        false
    end
  end
end
