defmodule Membrane.MoQ.Test.Relay do
  @moduledoc """
  NOTE: This test support module was LLM-generated.

  Runs a MoQ relay for integration tests as a regular supervised process.
  Start one per test module in `setup_all` for a relay shared by the module's
  tests, or inside a single test when it needs its own instance — e.g. to stop
  it mid-test and observe session-drop handling:

      setup_all do
        [relay: Relay.start_supervised!()]
      end

  Ensures TCP is used for lossless transport,
  but groups can still be dropped as part of eviction policies.

  Proper teardown is ensured via `MuonTrap.Daemon`.
  """

  use GenServer

  @ready_timeout_ms 15_000
  @probe_interval_ms 100

  @type relay :: %{url: String.t(), disable_tls_verify?: boolean()}

  @spec start_link(term()) :: GenServer.on_start()
  def start_link(_init_arg \\ nil), do: GenServer.start_link(__MODULE__, nil)

  @spec start_supervised!() :: relay()
  def start_supervised!() do
    __MODULE__ |> ExUnit.Callbacks.start_supervised!() |> relay()
  end

  @doc "URL and connection options of the relay run by the given server."
  @spec relay(GenServer.server()) :: relay()
  def relay(server), do: GenServer.call(server, :relay, :infinity)

  @impl true
  def init(nil) do
    binary = find_binary!()
    port_number = free_port!()
    config_path = write_config!(port_number)

    {:ok, _daemon} =
      MuonTrap.Daemon.start_link(binary, [config_path],
        stderr_to_stdout: true,
        log_output: :debug,
        log_prefix: "moq-relay: ",
        exit_status_to_reason: &{:moq_relay_exited, &1}
      )

    await_ready!(port_number)

    File.rm!(config_path)

    {:ok, %{url: "tcp://127.0.0.1:#{port_number}", disable_tls_verify?: false}}
  end

  @impl true
  def handle_call(:relay, _from, relay), do: {:reply, relay, relay}

  defp find_binary!() do
    System.get_env("MOQ_RELAY") || System.find_executable("moq-relay") ||
      raise """
      no moq-relay binary for the integration tests; provide one of:
        * MOQ_RELAY — path to a moq-relay binary
        * moq-relay on $PATH (e.g. installed with `cargo install moq-relay`)
      """
  end

  defp free_port!() do
    {:ok, socket} = :gen_tcp.listen(0, reuseaddr: true)
    {:ok, port_number} = :inet.port(socket)
    :ok = :gen_tcp.close(socket)
    port_number
  end

  defp write_config!(port_number) do
    path = Path.join(System.tmp_dir!(), "membrane-moq-test-relay-#{port_number}.toml")

    File.write!(path, """
    # Generated by #{inspect(__MODULE__)}; safe to delete.
    [log]
    level = "info"

    [server]
    tcp.bind = "127.0.0.1:#{port_number}"

    [auth]
    public = ""
    """)

    path
  end

  defp await_ready!(port_number) do
    deadline = System.monotonic_time(:millisecond) + @ready_timeout_ms
    await_ready_loop(port_number, deadline)
  end

  defp await_ready_loop(port_number, deadline) do
    cond do
      probe(port_number) ->
        :ok

      System.monotonic_time(:millisecond) > deadline ->
        raise """
        moq-relay did not become ready within #{@ready_timeout_ms} ms; \
        its output is forwarded to the Logger at debug level
        """

      true ->
        Process.sleep(@probe_interval_ms)
        await_ready_loop(port_number, deadline)
    end
  end

  defp probe(port_number) do
    case :gen_tcp.connect(~c"127.0.0.1", port_number, [:binary, active: false], 1_000) do
      {:ok, socket} ->
        :gen_tcp.close(socket)
        true

      {:error, _reason} ->
        false
    end
  end
end
