[package]
name = "moq"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
moq-net = "0.1.11"
moq-native = "0.17.1"
hang = "0.19.1"
moq-mux = "0.5.5"
url = "2.5.8"
rustler = "0.38.0"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
bytes = "1"
anyhow = "1.0.102"
