[package]
name = "moq"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
moq-lite = "0.17.0"
moq-native = "0.14.1"
hang = "0.16.0"
moq-mux = "0.4.1"
url = "2.5.8"
rustler = "0.37.3"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
bytes = "1"
anyhow = "1.0.102"
